"""create phase 2 core schema

Revision ID: 20260825_0001
Revises:
Create Date: 2026-08-25 19:12:58.771166
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260825_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.Column(
            "seniority",
            sa.Enum(
                "TRAINEE",
                "JUNIOR",
                "ENGINEER",
                "SENIOR",
                "STAFF",
                "PRINCIPAL",
                name="agent_seniority",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "ASSIGNED",
                "WORKING",
                "WAITING",
                "BLOCKED",
                "OFFLINE",
                name="agent_status",
            ),
            nullable=False,
        ),
        sa.Column("autonomy_level", sa.Integer(), nullable=False),
        sa.Column("reputation_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("reliability_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "autonomy_level BETWEEN 0 AND 5", name=op.f("ck_agents_autonomy_level_range")
        ),
        sa.CheckConstraint(
            "reliability_score BETWEEN 0 AND 1", name=op.f("ck_agents_reliability_score_range")
        ),
        sa.CheckConstraint(
            "reputation_score BETWEEN 0 AND 1", name=op.f("ck_agents_reputation_score_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_index(op.f("ix_agents_slug"), "agents", ["slug"], unique=True)
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "INTAKE",
                "DISCOVERY",
                "PLANNING",
                "APPROVED",
                "IN_PROGRESS",
                "STAGING",
                "CLIENT_REVIEW",
                "COMPLETED",
                "ARCHIVED",
                "PAUSED",
                "CANCELLED",
                name="project_status",
            ),
            nullable=False,
        ),
        sa.Column("client_name", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        "ix_projects_status_created_at", "projects", ["status", "created_at"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("parent_task_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "READY",
                "ASSIGNED",
                "IN_PROGRESS",
                "WAITING_REVIEW",
                "REJECTED",
                "BLOCKED",
                "WAITING_HUMAN",
                "DONE",
                "CANCELLED",
                name="task_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="task_priority"),
            nullable=False,
        ),
        sa.Column("assigned_agent_id", sa.UUID(), nullable=True),
        sa.Column("acceptance_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_iterations", sa.Integer(), nullable=False),
        sa.Column("iteration_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_iterations >= 1 AND iteration_count >= 0 AND iteration_count <= max_iterations",
            name=op.f("ck_tasks_iteration_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_agent_id"],
            ["agents.id"],
            name=op.f("fk_tasks_assigned_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["tasks.id"],
            name=op.f("fk_tasks_parent_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_tasks_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(
        "ix_tasks_assigned_agent_status", "tasks", ["assigned_agent_id", "status"], unique=False
    )
    op.create_index(op.f("ix_tasks_parent_task_id"), "tasks", ["parent_task_id"], unique=False)
    op.create_index("ix_tasks_project_status", "tasks", ["project_id", "status"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                "TIMED_OUT",
                name="agent_run_status",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_agent_runs_confidence_range"),
        ),
        sa.CheckConstraint("iteration >= 1", name=op.f("ck_agent_runs_iteration_positive")),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_runs_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_agent_runs_task_id_tasks"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        "ix_agent_runs_agent_status", "agent_runs", ["agent_id", "status"], unique=False
    )
    op.create_index("ix_agent_runs_created_at", "agent_runs", ["created_at"], unique=False)
    op.create_index("ix_agent_runs_task_status", "agent_runs", ["task_id", "status"], unique=False)
    op.create_table(
        "agent_scores",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column(
            "score_type",
            sa.Enum(
                "CONFIDENCE",
                "RELIABILITY",
                "EXPERTISE",
                "CODE_QUALITY",
                "SECURITY",
                "COLLABORATION",
                "CUSTOMER_SATISFACTION",
                name="agent_score_type",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("REVIEW", "QA", "SECURITY", "FEEDBACK", "SYSTEM", name="score_source_type"),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("value BETWEEN 0 AND 1", name=op.f("ck_agent_scores_value_range")),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_scores_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_agent_scores_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_agent_scores_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_scores")),
    )
    op.create_index(op.f("ix_agent_scores_agent_id"), "agent_scores", ["agent_id"], unique=False)
    op.create_index(
        "ix_agent_scores_agent_type_created",
        "agent_scores",
        ["agent_id", "score_type", "created_at"],
        unique=False,
    )
    op.create_index("ix_agent_scores_project_id", "agent_scores", ["project_id"], unique=False)
    op.create_index("ix_agent_scores_task_id", "agent_scores", ["task_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("alternatives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", "SUPERSEDED", name="decision_outcome"),
            nullable=False,
        ),
        sa.Column("final_result", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_decisions_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_decisions_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_decisions_task_id_tasks"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_index(
        "ix_decisions_agent_created_at", "decisions", ["agent_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_decisions_outcome_created_at", "decisions", ["outcome", "created_at"], unique=False
    )
    op.create_index(
        "ix_decisions_task_created_at", "decisions", ["task_id", "created_at"], unique=False
    )
    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_task_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "task_id <> depends_on_task_id", name=op.f("ck_task_dependencies_no_self_dependency")
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_task_id"],
            ["tasks.id"],
            name=op.f("fk_task_dependencies_depends_on_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_dependencies_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_dependencies")),
        sa.UniqueConstraint("task_id", "depends_on_task_id", name="uq_task_dependencies_task_id"),
    )
    op.create_index(
        "ix_task_dependencies_depends_on_task_id",
        "task_dependencies",
        ["depends_on_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_dependencies_task_id"), "task_dependencies", ["task_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column(
            "actor_type",
            sa.Enum(
                "AGENT", "HUMAN", "SYSTEM", "WORKER", "TOOL", "WEBHOOK", name="audit_actor_type"
            ),
            nullable=True,
        ),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("agent_run_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=255), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column(
            "result",
            sa.Enum("SUCCEEDED", "FAILED", "DENIED", "CANCELLED", name="audit_result"),
            nullable=False,
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("corrects_event_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_audit_events_agent_run_id_agent_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["corrects_event_id"],
            ["audit_events.id"],
            name=op.f("fk_audit_events_corrects_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audit_events_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_audit_events_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_corrects_event_id", "audit_events", ["corrects_event_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_correlation_id", "audit_events", ["correlation_id"], unique=False
    )
    op.create_index("ix_audit_events_created_at", "audit_events", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_events_project_created",
        "audit_events",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_run_created", "audit_events", ["agent_run_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_task_created", "audit_events", ["task_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_type_created", "audit_events", ["event_type", "created_at"], unique=False
    )
    op.create_table(
        "tool_calls",
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "DENIED",
                "TIMED_OUT",
                name="tool_call_status",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_tool_calls_agent_run_id_agent_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
    )
    op.create_index("ix_tool_calls_created_at", "tool_calls", ["created_at"], unique=False)
    op.create_index(
        "ix_tool_calls_run_status", "tool_calls", ["agent_run_id", "status"], unique=False
    )
    op.create_index("ix_tool_calls_tool_name", "tool_calls", ["tool_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_calls_tool_name", table_name="tool_calls")
    op.drop_index("ix_tool_calls_run_status", table_name="tool_calls")
    op.drop_index("ix_tool_calls_created_at", table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index("ix_audit_events_type_created", table_name="audit_events")
    op.drop_index("ix_audit_events_task_created", table_name="audit_events")
    op.drop_index("ix_audit_events_run_created", table_name="audit_events")
    op.drop_index("ix_audit_events_project_created", table_name="audit_events")
    op.drop_index("ix_audit_events_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_correlation_id", table_name="audit_events")
    op.drop_index("ix_audit_events_corrects_event_id", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_task_dependencies_task_id"), table_name="task_dependencies")
    op.drop_index("ix_task_dependencies_depends_on_task_id", table_name="task_dependencies")
    op.drop_table("task_dependencies")
    op.drop_index("ix_decisions_task_created_at", table_name="decisions")
    op.drop_index("ix_decisions_outcome_created_at", table_name="decisions")
    op.drop_index("ix_decisions_agent_created_at", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index("ix_agent_scores_task_id", table_name="agent_scores")
    op.drop_index("ix_agent_scores_project_id", table_name="agent_scores")
    op.drop_index("ix_agent_scores_agent_type_created", table_name="agent_scores")
    op.drop_index(op.f("ix_agent_scores_agent_id"), table_name="agent_scores")
    op.drop_table("agent_scores")
    op.drop_index("ix_agent_runs_task_status", table_name="agent_runs")
    op.drop_index("ix_agent_runs_created_at", table_name="agent_runs")
    op.drop_index("ix_agent_runs_agent_status", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_tasks_project_status", table_name="tasks")
    op.drop_index(op.f("ix_tasks_parent_task_id"), table_name="tasks")
    op.drop_index("ix_tasks_assigned_agent_status", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_projects_status_created_at", table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_agents_slug"), table_name="agents")
    op.drop_table("agents")
    for enum_name in (
        "tool_call_status",
        "audit_result",
        "audit_actor_type",
        "decision_outcome",
        "score_source_type",
        "agent_score_type",
        "agent_run_status",
        "task_priority",
        "task_status",
        "project_status",
        "agent_status",
        "agent_seniority",
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
