"""Provider-neutral bounded Git workflow contracts."""

from core.git_workflow.audit import GIT_AUDIT_DATA_KEYS, GitAuditRecord, GitAuditStage
from core.git_workflow.errors import GitWorkflowError, GitWorkflowErrorCode
from core.git_workflow.types import (
    CommitKind,
    CommitPolicyDecision,
    CommitPolicyResult,
    CommitRequest,
    CreateTaskBranchRequest,
    GitAuthority,
    GitCheckStatus,
    GitCommitResult,
    GitCommitSummary,
    GitDiffMode,
    GitDiffRequest,
    GitDiffResult,
    GitEvidenceReference,
    GitHistoryRequest,
    GitHistoryResult,
    GitIdentity,
    GitOperation,
    GitProcessLimits,
    GitRepositoryStatus,
    GitWorkflowContext,
    MergeDecision,
    MergeReasonCode,
    MergeValidationResult,
    PreparePullRequestRequest,
    PullRequestPreparation,
    TaskBranchKind,
    TaskBranchResult,
    ValidateMergeRequirementsRequest,
    derive_task_branch,
    is_protected_branch,
    is_valid_sha,
)
from core.git_workflow.workflow import GitWorkflow

__all__ = [
    "GIT_AUDIT_DATA_KEYS",
    "CommitKind",
    "CommitPolicyDecision",
    "CommitPolicyResult",
    "CommitRequest",
    "CreateTaskBranchRequest",
    "GitAuthority",
    "GitAuditRecord",
    "GitAuditStage",
    "GitCheckStatus",
    "GitCommitResult",
    "GitCommitSummary",
    "GitDiffMode",
    "GitDiffRequest",
    "GitDiffResult",
    "GitEvidenceReference",
    "GitHistoryRequest",
    "GitHistoryResult",
    "GitIdentity",
    "GitOperation",
    "GitProcessLimits",
    "GitRepositoryStatus",
    "GitWorkflowContext",
    "GitWorkflow",
    "GitWorkflowError",
    "GitWorkflowErrorCode",
    "MergeDecision",
    "MergeReasonCode",
    "MergeValidationResult",
    "PreparePullRequestRequest",
    "PullRequestPreparation",
    "TaskBranchKind",
    "TaskBranchResult",
    "ValidateMergeRequirementsRequest",
    "derive_task_branch",
    "is_protected_branch",
    "is_valid_sha",
]
