"""Provider-neutral contracts for bounded remote Git hosting operations."""

from core.git_providers.errors import RemoteGitError, RemoteGitErrorCode
from core.git_providers.ports import (
    GitHubTokenProvider,
    RemoteGitAuditSink,
    RemoteGitProvider,
    RemoteMergeGate,
)
from core.git_providers.types import (
    MAX_FILE_CONTENT_BYTES,
    CreateRemoteBranchRequest,
    CreateRemotePullRequestRequest,
    RemoteBranch,
    RemoteCheck,
    RemoteCheckConclusion,
    RemoteChecksRequest,
    RemoteCheckStatus,
    RemoteCommitRequest,
    RemoteCommitResult,
    RemoteFileChange,
    RemoteGitAuditEvent,
    RemoteGitAuditOutcome,
    RemoteGitOperation,
    RemoteMergeMethod,
    RemoteMergeRequest,
    RemoteMergeResult,
    RemoteOperationOptions,
    RemotePullRequest,
    RemotePullRequestRequest,
    RemotePullRequestState,
    RemoteRepositoryMetadata,
    RemoteReview,
    RemoteReviewState,
    RepositoryCoordinates,
)

__all__ = [
    "MAX_FILE_CONTENT_BYTES",
    "CreateRemoteBranchRequest",
    "CreateRemotePullRequestRequest",
    "GitHubTokenProvider",
    "RemoteBranch",
    "RemoteCheck",
    "RemoteCheckConclusion",
    "RemoteChecksRequest",
    "RemoteCheckStatus",
    "RemoteCommitRequest",
    "RemoteCommitResult",
    "RemoteFileChange",
    "RemoteGitAuditEvent",
    "RemoteGitAuditOutcome",
    "RemoteGitAuditSink",
    "RemoteGitError",
    "RemoteGitErrorCode",
    "RemoteGitOperation",
    "RemoteGitProvider",
    "RemoteMergeGate",
    "RemoteMergeMethod",
    "RemoteMergeRequest",
    "RemoteMergeResult",
    "RemoteOperationOptions",
    "RemotePullRequest",
    "RemotePullRequestRequest",
    "RemotePullRequestState",
    "RemoteRepositoryMetadata",
    "RemoteReview",
    "RemoteReviewState",
    "RepositoryCoordinates",
]
